### ISSUE TITLE
jade virtualdom

### ISSUE THREAD

**Issue by jonathanong** [jonathanong/ideas#3]
browserify / webpack / etc. plugin using a custom jade compiler to convert jade -> [virtual-dom](https://www.npmjs.com/package/virtual-dom). i personally don't like react, angular, etc. too much.

kind of waiting on jade 2.0.0 to even start this.

**Comment by Swatinem** [comment]
Probably also make it configurable, so you can us it with any kind of virtual-dom like library.

**Comment by jonathanong** [comment]
sounds difficult O.O
